<?php

namespace AppBundle\Repository;

/**
 * MagnetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagnetRepository extends \Doctrine\ORM\EntityRepository
{
}
